version: "3"

services:
  server:
    image: zoomgif:3.8.5
    build:
      context: ./modules
      dockerfile: DOCKERFILE_SERVER
    ports:
      - "5000:5000"
    volumes:
      - ./modules:/app
    command: "python webpage.py"
    restart: always
    environment:
      - HOSTNAME=broker
  worker:
    image: zoomgif:3.8.5
    volumes:
      - ./modules:/app/
    command: bash -c "cd backend & celery -A backend worker --loglevel=info -P threads --autoscale=2,2"
    depends_on:
      - broker
    restart: always
    environment:
      - HOSTNAME=broker
  broker:
    image: rabbitmq:3.8.5-management
    hostname: broker
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5674:5672"
      - "15674:15672"
    restart: always
